### ISSUE TITLE
Create a way back to the portal from TSA

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#136] opened 2018-01-24 15:44 UTC
Currently clicking on the EnviroDIY logo does nothing.

**Comment by SRGDamia1** [comment] 2018-04-30 15:10
Once you enter TimeSeriesAnalyst, it feels like you're lost in a totally different system with no idea how you got there or how to get back.

**Comment by horsburgh** [comment] 2018-05-16 20:12
@SRGDamia1 - per our conversation today, it would be great to get a few more details here so that we know exactly what is needed.

**Comment by horsburgh** [comment] 2018-07-25 19:40
After discussing this quite a bit within our group, this presents a difficult problem. The data sharing portal and the TSA are, in fact, two different software applications. This is by design. In order to keep the code base for TSA free of project-specific links (because we are using TSA for multiple projects), we do not want to add EnviroDIY-specific links to the TSA. 

Also, the convention in web development is that a link in the title bar at the top of a page should take you to the root/home page of a site - e.g., the EnviroDIY logo in the TSA should take you to the root page of TSA (data.envirodiy.org/tsa) and not to data.envirodiy.org. Another challenge is that user data is never transferred to TSA, so the two sites cannot technically share the same top navigation because the login information is not transferred. 

As a solution, we have verified that the links to TSA from the data sharing portal open in a new browser tab so that the user is never directed away from the data sharing portal. The data sharing portal will always stay open in its own browser tab.

**Comment by horsburgh** [comment] 2018-07-26 22:04
@Maurier, @jcaraballo17, and @darksinge - I see the old links to the TSA from each of the sparkline tiles, but I don't see the new navigation link at the top and the new button @Maurier added to launch the TSA. I want to verify that those open in a new window. As soon as the sandbox has been updated with these changes, I think we can call this one tested.

**Comment by horsburgh** [comment] 2018-08-02 00:31
The links to TSA are all present and opening in a new browser tab. I'm adding the "tested" label to this one.

**Comment by horsburgh** [comment] 2018-08-14 14:30
Links to new browser tabs are live on production. Closing.

**Closed by horsburgh** 2018-08-14 14:30 UTC
Labels: WebTSA, feature request, high priority, ready for testing, tested
