### ISSUE TITLE
Fix csv header reader 

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#416] opened 2019-07-31 14:49 UTC
https://github.com/ODM2/ODM2DataSharingPortal/blob/b95ca4356d73466a5ccf0298b122a38cad8fcfde/src/dataloaderservices/views.py#L189

I wrote this function, but because it's looking for an element in the row, it means the csv to upload (rather obnoxiously) requires a comma after the feature UUID if it's alone in a row, because the row[0] requires that the row was read as a list not just as a string.  I'm sure it's a really easy fix to make the code not error out without the comma, but I don't know the fix.  I also can't test anything because I have had no success getting working app to work locally.  (https://github.com/ODM2/ODM2DataSharingPortal/issues/376...)

**Comment by SRGDamia1** [comment] 2019-07-31 15:11
Also apply the fix such that the "Date and Time in UTC###" header could be alone on a row.

https://github.com/ODM2/ODM2DataSharingPortal/blob/b95ca4356d73466a5ccf0298b122a38cad8fcfde/src/dataloaderservices/views.py#L215

**Comment by htaolimno** [comment] 2019-08-02 03:09
@SRGDamia1 could you please send me an example *.csv file for debugging and testing purpose ?

**Comment by aufdenkampe** [comment] 2019-08-02 11:50
@SRGDamia1, it would be great if you could email a file that now fails to upload but that you would like to pass.  Thanks.

**Comment by SRGDamia1** [comment] 2019-08-02 12:45
Put some in the google drive folder: https://drive.google.com/drive/u/1/folders/1pJk3SQqr06_IsvD_QEV4tCJgtZ65_GxY

It's this comma that I want not to need:
![image](https://user-images.githubusercontent.com/5374350/62371065-d71b5c00-b501-11e9-9c05-65b58524f587.png)

**Comment by htaolimno** [comment] 2019-08-04 02:16
code fix committed to the development branch.

**Comment by htaolimno** [comment] 2019-08-05 15:15
@SRGDamia1 would you please spend a few minutes testing the *.csv import again. I am new to the project and don't have an active site ready for testing the functionality.

**Comment by aufdenkampe** [comment] 2019-08-05 17:19
@htaolimno, those files each have a site code in there name, which translate to these web pages:
- https://staging.monitormywatershed.org/sites/BCRC9S/
- https://staging.monitormywatershed.org/sites/ROCK_DS2/

To test the manual upload:
1. scroll down to the "Sensor Observations..." panel and click on the green "Manage Sensors" button, and
2. scroll down to the "Upload a data file (.csv)" panel and click on the green button with a paperclip symbol.

**Comment by htaolimno** [comment] 2019-08-05 18:05
@aufdenkampe  First I didn't see the green "Manage Sensors" button, but I quickly realized that I should assign myself a admin role. I just tested uploading to site BCRC9S a csv file whose first line does not end with a comma and it went through fine. I consider the issue is fixed and issue closed.

**Closed by htaolimno** 2019-08-05 18:05 UTC
Labels: ready for testing

**Comment by SRGDamia1** [comment] 2019-08-05 18:26
Thanks!

**Comment by aufdenkampe** [comment] 2019-08-05 18:27
@htaolimno, thanks! Yes, I forgot to mention that you need to login as Admin.
