### ISSUE TITLE
CSV upload is failing to add data to certain variables

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#443] opened 2019-10-28 21:38 UTC
First posted by Jim Moore here:  https://www.envirodiy.org/topic/missing-data-with-manual-upload-to-mmw/

Uploading a file with four variables, data is added to three of them by the fourth one (actually the first in order) is not being attached.  I've confirmed that the structure and all of the UUID's are correct and attempted to upload it myself but I get the same result.

**Comment by w3asa** [comment] 2019-11-27 17:28
I have started fresh with my GMi_ sensor stations and dropped the # so now TSA links to the specific stations variables rather than the overview map.  However, still dropping the first variable and I have followed the [procedure](https://www.dropbox.com/s/a8v2mkkkpgzksj1/Updates_usergroupmeeting_Oct18%2C2019_v3.pdf?dl=0) outlined by Dave Bressler.  
I uploaded SL150 this morning and no lost variabes however I got an FtU error with a week of data and same error with 4 days of data.  one day of data and "...success".  However, TSA showed all the data that I had attempted to upload.  i.e. the error message seems to be in error!
Any help on this would be appreciated.  I can supply the header data for SL150 and the GMI_ sensor stations if needed.

**Comment by w3asa** [comment] 2019-12-10 17:17
This file won't upload to GMI_WX or GMI_WX2 and no errors generated.  The upload process shows "success..." immediately but no data was uploaded.
[WXdata11-26.txt](https://github.com/ODM2/ODM2DataSharingPortal/files/3946256/WXdata11-26.txt)

**Comment by w3asa** [comment] 2019-12-10 17:19
btw its really a .csv file masquerading as .txt since apparently github doesn't like .csv files

**Comment by w3asa** [comment] 2019-12-30 16:38
I have been manually uploading from SL150 (BCMC4S)since its not communicating with mother ship.  This has been uploading successfully and displaying properly on TSA.  However when I attempted to fill in missing data from 12/11@17:30Z to 12/15@15:00Z it uploaded successfully but it did not appear in TSA.  This data was missing in the TSA export data base but was present in the download file: BCMC4S_TimeSeriesResults.csv

I have been putting all my upload issues in this thread.  Comments?

**Comment by aufdenkampe** [comment] 2020-01-03 18:10
@w3asa, thanks for posting this issue and following up with updates. 

If I understand correctly, the primary issue has been resolved but your only issue is that TSA shows a data gap for https://monitormywatershed.org/sites/BCMC4S/ for Dec. 11-15 even after you successfully uploaded the CSV file. Is that correct?

If so, let's rename this issue to better reflect the existing problem.

BTW, I have confirmed that your Dec. 11-15 do exist in the downloaded CSV but do not appear in TSA, even after 4 days since you updated them.

We may need to bump this issue to the [Release 0.12 - Tech Debt / Refactor Code](https://github.com/ODM2/ODM2DataSharingPortal/milestone/14) milestone, for which we plan on restructuring the code behind CSV handling and TSA connectivity. The existing code libraries and structures for these functions are not optimal and have given us tons of trouble for a long time, and we feel it best to redo these functions from scratch. However, we don't have funding for this work, so I can't promise a timeline.

Thanks for your patience on this. We had a number of minor database issues this fall that we resolved, which I wanted to address before tackling your issue.

**Comment by aufdenkampe** [comment] 2020-01-03 18:30
This appears to be related issue #430  **Uploaded data not appearing / not filling gaps**

**Comment by w3asa** [comment] 2020-01-04 01:23
I agree it should be under the #430 issue.  Not sure of the protocol - can you handle this or should I repost on issue #430?  
The other issues that I have noted with the GMI_... sites have not been resolved.  The missing first variable I can live with but the weather data  issue with GMI_WX is more critical for the data set needed for environmental studies of Great Marsh.

**Comment by aufdenkampe** [comment] 2020-01-05 20:11
@w3asa, thanks for the clarification. So it doesn't sound like a complete duplicate of #430, because some data aren't showing up at all. I'll look at it a bit more closely next week.

**Comment by w3asa** [comment] 2020-04-02 15:38
I uploaded data to my GMI_EC2 station yesterday using DRWI_CitSci code after first deleting the original station and registering a new station with the same name and parameter list.  It worked with all four variables showing on TSA.  Who knows why?  Perhaps magic incantations from the DRWI code!

**Comment by aufdenkampe** [comment] 2021-11-29 21:53
I think this has been fixed with #526, so closing.

We will further improve performance in the future with #312.

**Closed by aufdenkampe** 2021-11-29 21:53 UTC
Labels: bug
