### ISSUE TITLE
adding custom y-axis range, similar to x-axis date selection

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#457] opened 2020-01-23 20:04 UTC
Would be useful to incorporate an option to actually enter specific ranges for y-axis (in addition to dragging/scrolling with mouse or pad) - you can do this on the x-axis in the upper right calendar selection option and it seems like it would be useful to be able to do the same for the parameter(s) values displayed on the y-axis.

**Comment by aufdenkampe** [comment] 2021-11-02 17:26
We have decided to replace TSA with a Time Series Visualization (TSV) page, starting with:
- #512

Check out the screenshots I just posted with https://github.com/ODM2/ODM2DataSharingPortal/issues/512#issuecomment-957935317. 

We'll add this to our list of feature requests for TSV.

**Comment by aufdenkampe** [comment] 2022-03-21 20:40
Closing this, as it is now a duplicate of:
- #540

**Closed by aufdenkampe** 2022-03-21 20:40 UTC
Labels: feature request, tsa-related
