### ISSUE TITLE
500 Server Error on Admin Page

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#314] opened 2018-10-23 16:52 UTC
I cannot modify a variable or add a sensor output.  I'm getting a 500 server error.

**Comment by jcaraballo17** [comment] 2018-10-23 17:28
This issue came up in #292. It's fixed, but it has to go through the sandbox and will be up in the next deployment.

**Comment by SRGDamia1** [comment] 2022-03-18 21:06
Broken again

**Comment by aufdenkampe** [comment] 2022-03-21 17:46
@ptomasula, could you look into this bug?

I'm wondering if it is connected to our Django upgrades?

**Comment by aufdenkampe** [comment] 2022-04-04 21:11
Closing this because it is a duplicate of:
- #577

**Closed by aufdenkampe** 2022-04-04 21:11 UTC
Labels: bug, high priority
