### ISSUE TITLE
sparkline plots not showing last reporting time

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#560] opened 2022-02-25 20:47 UTC
The small visualization TSA's seem to be not showing the last time a POST was made.
https://monitormywatershed.org/sites/SSU_ENG_SD02/
![image](https://user-images.githubusercontent.com/2766619/155797947-0db168d8-9bb3-4abb-a1fa-0047452b4cc5.png)

This seems to be across a number of loggers, not just this one.

I would expect them to show the last time a connection was made.

**Comment by mbarneytu** [comment] 2022-04-07 18:42
@aufdenkampe Is there any chance we could get this bug fixed sooner -- specifically the missing "Last observation"? 

Field season is ramping up quickly, and our staff and volunteers are launching more than a dozen new monitoring stations, beginning today. The lack of a functional dashboard, and the gray pins on the map, is going to catch a lot of attention, especially when people notice that it works for some sites and not others. I had not noticed the issue until now because the display works correctly for existing sites.

The targeted release 0.14 is still six weeks out, and this missing "Last observation" issue was identified 6 months ago, before the new MMW was even in production (see https://github.com/ODM2/ODM2DataSharingPortal/issues/511#issue-1030563807). I feel that this bug is high-profile enough that a hot-fix should be decoupled from a larger release if that will resolve it sooner.

This has also been [reported on the EnviroDIY forum](https://www.envirodiy.org/topic/data-uploading-but-not-publishing/) in early March, without a response from the MMW team. Given its impact - for Mayfly users of all levels - I feel that the EnviroDIY community needs to be kept informed about the status of bugs like this.

**Comment by aufdenkampe** [comment] 2022-04-07 18:50
@mbarneytu, thanks for pinging me on this. When I did the triage of issues a couple of weeks ago, I think I somehow failed to recognize that this particular issue is more of a bug than a feature request.

Although we're moving o the next milestone task #551, which fixes a number of deeper issues with time management, this particular feature was working in our last release, so something odd got broken this winter.

**Comment by ScottEnsign** [comment] 2022-04-13 11:14
@aufdenkampe, I also wanted to weigh-in on the severity of this bug for demonstrating functionality for new users. We are hosting a workshop with new users from across the Delmarva on Thursday, April 14, and this bug is going to require us to find a workaround instead of using Monitor My Watershed. We can't easily demonstrate real-time data functionality without this bug being fixed.

**Comment by ptomasula** [comment] 2022-04-26 21:02
The core cause of this issue is rooted in having separate databases with redundant (and sometimes conflicting) information. The last reporting time is stored in a separate data table, which do not have an implicit link to the timeseriesresultvalues table or any constraint in the database which forces consistency. Instead the task of keeping the tables in sync is reliant on a code solution which is not very stable and has a low fault tolerance. The ultimate fix to this that will resolve this issue permanently is additional refactoring to eliminate the redundant data tables and move to a pure ODM2 database (see #550). However recognizing how critical this issue is, we took steps to restore this functionality while we work towards that ultimate solution.  

1. We created a database function that syncs the tables on the insert of new data into the timeseriesresultvalues table. This shifts the burdened on keeping the tables in sync from the application, to the database, which should result in more consistent syncing between the two tables.   
2. We revised the application's API code to reduce its responsibility. It is now only responsible for creating an initial sensormeasurement record if one does not exist. We also corrected a bug that in query.
3. We created a database function that allows us to manually run this syncing operation on the whole dataloader_sensormeasurements table, which gives us a better hot fix solution if that data ever gets out of sync (such as the present case on the production server). 

These improvements are live on the staging server, and will be live on production following our release of V0.13.0.

**Comment by mbarneytu** [comment] 2022-04-27 15:06
Thank you for prioritizing this issue @ptomasula! 

Even on Staging, our newer sites still don't display the latest values, and their pins on the map are still grey, despite them having data within the last 12 hours. Is that what you would expect, given the new improvements listed above?
https://staging.monitormywatershed.org/sites/Boulder_Upstream/
https://staging.monitormywatershed.org/sites/Boulder_Downstream/
https://staging.monitormywatershed.org/sites/Paint%20Creek%20Rochester%20MP/

@aufdenkampe @ScottEnsign

**Comment by aufdenkampe** [comment] 2022-04-27 20:54
@mbarneytu, thanks for reporting that the issue isn't fixed for newer sites. I'm seeing the same:

This older site looks good:
- https://staging.monitormywatershed.org/sites/VLA1-Oakmede/

This new site doesn't have a Last Observation timestamp or value:
- https://staging.monitormywatershed.org/sites/RHA01/

@ptomasula, is there any chance you can look into a quick-fix for this priority issue, as the community starts deploying new stations for the coming field season?

**Comment by ptomasula** [comment] 2022-04-27 21:15
@aufdenkampe @mbarneytu 
Thanks for following up on this issue. I think this will be resolved once we release and new configuration starts receiving the API traffic. 

I believe staging server does not correctly display the latest result field for new sites, because there is no dataloader_sensormeasurement record to be updated. My latest changes moves the responsibility of update an existing dataloader_sensor records to the database; however the initial creation of this record is still the responsibility of the API code. The combination of a bug on production which prevents these records for being created (fixed on staging), and the fact that our syncing of data to the staging server is handled through a direct data dump and not the API leds me to believe this is behavior as expected for now. I would expect that once the code on staging is live and starts receive API traffic, the new sites will display correctly. If that's not the case I'll plan to follow-up on this ASAP.

**Comment by ptomasula** [comment] 2022-04-28 16:31
Our release is now live on production and these new sites do appear to be displaying the last observations timestamp. 

@aufdenkampe One observation is the RHA01 site which is in NJ appears to are showing the time as 1 hour behind. Indeed all EST sites appear to be one hour behind. We'll have to look this further. I seem to recall we encountered this before, so we'll have to find that issue and address this.

**Comment by mbarneytu** [comment] 2022-04-28 16:55
Our new sites are indeed displaying their latest observations now - thank you!

**Comment by neilh10** [comment] 2022-04-28 17:14
This site is still not showing https://monitormywatershed.org/sites/SSU_ENG_SD02/
It was last updated Apr/25 15:12

![image](https://user-images.githubusercontent.com/2766619/165807988-662d1dff-af4e-4e9e-81b8-528157f0c956.png)

**Comment by ptomasula** [comment] 2022-04-28 17:54
Thanks @neilh10, 

I'm not seeing that any new data has come in for that site, since the 25th. As I mentioned above the API code is still responsible for creating an initial record that is used to display that observation. Up until our release, that logic was also broken on production. In order for the Last Observation to appear correctly some new API traffic will need to hit the server. 

I supposed we could also develop a query to do a 1 time check for missing records and manually create them as necessary.

**Comment by neilh10** [comment] 2022-04-28 18:44
@ptomasula thats OK, if it shows up when new data hits it. I'll let the students using it know it should be fixed, as they use it in a presentation.

**Comment by aufdenkampe** [comment] 2022-04-29 16:12
Based on my quick check of theses test links, it all appears to be working! Yay!
* https://monitormywatershed.org/sites/Boulder_Upstream/
* https://monitormywatershed.org/sites/Boulder_Downstream/
* https://monitormywatershed.org/sites/Paint%20Creek%20Rochester%20MP/
* https://monitormywatershed.org/sites/SSU_ENG_SD02/
* https://monitormywatershed.org/sites/RHA01/

Thanks all for testing!
Thanks @ptomasula for fixing this critical issue, just in time for field season!

**Closed by aufdenkampe** 2022-04-29 16:12 UTC
Labels: bug

**Comment by neilh10** [comment] 2022-04-29 17:34
Yeah -  
https://monitormywatershed.org/sites/SSU_ENG_SD02/
was updated once a POST was made.

**Comment by SRGDamia1** [comment] 2022-04-29 19:57
@ptomasula I think you *should* do the one-time query for sites, just to be safe.
