### ISSUE TITLE
Forgot Password server error

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#561] opened 2022-02-28 21:03 UTC
[Reported](https://www.envirodiy.org/topic/forgot-password-server-error/) on EnviroDIY.org Monitor My Watershed forum: We are seeing a Server Error 500 getting returned from a Forgot Password request on Monitor My Watershed.

**Comment by HeatherBrooks** [comment] 2022-02-28 21:17
I'm also getting the 500 error when I save changes in My Account.

**Comment by aufdenkampe** [comment] 2022-03-21 17:18
@ptomasula, can you look into this bug?

**Comment by HeatherBrooks** [comment] 2022-03-22 19:28
@ptomasula @aufdenkampe Just had another report of this. Hoping this is a quick fix as we have people registering on the site in preparation for the next EnviroDIY Monitoring Station workshop.

**Comment by aufdenkampe** [comment] 2022-04-04 21:14
This looks connected to:
- #577

**Comment by ptomasula** [comment] 2022-04-21 21:06
I did some of the initial fixes, which now enable the password forms to display. However; it is still not possible to reset a password.
After looking into this for a bit, I believe it might be our email service provider blocking connection through smtp. At a minimum I can confirm that reset email is never sent out from the email address. We'd like to try using a different email service provider before investing more time looking into this. We've recently started the process of transitioning to [SES](https://aws.amazon.com/ses/) and will revisit once that process is complete.

**Comment by ptomasula** [comment] 2022-04-27 21:55
We received approval for SES yesterday afternoon, and I worked on reconfiguring the email service for the application this morning. I was able to successfully reset the password and have deployed that code onto the [staging server](https://staging.monitormywatershed.org/). This should be fixed on production with our release of [v0.13.0](https://github.com/ODM2/ODM2DataSharingPortal/milestone/19)

**Comment by ptomasula** [comment] 2022-04-28 16:05
This appears to still be an issues on the production server even after our release. This likely means we have a configuration issue in production settings. We'll jump on that and report back.

**Comment by ptomasula** [comment] 2022-04-29 16:02
This was indeed due to a configuration error. One of the configuration changes from stating never made it over to our production settings. I've corrected that, and am pleased to report this appears to be functioning on production again.

**Closed by ptomasula** 2022-04-29 16:02 UTC
Labels: bug, high priority

**Comment by dbressler75** [comment] 2022-08-22 17:00
@ptomasula and @aufdenkampe, I tested the Forgot Password function this morning about 9a and have yet to receive an email (account: davidwbressler@gmail.com) with any instructions for resetting the password.  I don't need to reset the password but wanted to test it and it does not appear to be working.

**Comment by dbressler75** [comment] 2022-08-22 19:22
As a follow up, another user said they were able to get all the way to the point where they changed the password but then when they entered the new password it wouldn't work: "I actually got the whole way through to change my PW, but when I tried entering the new PW it wouldn't let me access the account.  I tried it a few times and it didn't work."

**Comment by dbressler75** [comment] 2022-08-22 19:24
Also, I think there may different issues with older accounts (such as the one I just mentioned with the other user) and newer accounts (such as my personal one that I described in the first post today).  Different issues but neither one resulted in successful password change.

**Comment by aufdenkampe** [comment] 2022-08-30 16:43
@dbressler75, thanks for your reporting on password reset emails not arriving. This function works for us, so I'm wondering if the emails are going to span or somehow getting filtered by your email system.

Also, in our upcoming Milestone for [v0.15 release - Refactor Authentication; Develop Organization Leader Roles](https://github.com/ODM2/ODM2DataSharingPortal/milestone/26), we plan on completely changing the way logins work, to leverage Amazon's more secure Cognito authentication system.

**Comment by dbressler75** [comment] 2022-08-30 16:48
@aufdenkampe , ok so presumably with the complete change in login process this issue will be dealt with at that time.  I'm pretty sure messages were not going to spam.  I've spoken with others have tried it and they were also not able to reset their password.
