### ISSUE TITLE
Sparklines, csv's, and pop up data tables are missing data

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#131] opened 2018-01-22 20:42 UTC
![capture2](https://user-images.githubusercontent.com/5374350/35243426-d44f2dc2-ff8a-11e7-9b88-5c3fe158b831.JPG)

**Comment by SRGDamia1** [comment] 2018-01-23 16:56
Are the sparklines, etc fed by the cached influx data or are they coming in via WOFpy or some other direct connection to the database?  [That is, should I expect them to be instantly updated or should I expect delays?}

**Comment by fryarludwig** [comment] 2018-01-23 19:50
The sparklines and data tables are fed by influx data. We can't use the regular database without significantly increasing loading time for sites with lots of sensors. We can reduce the influx data delay to as low as 15-30 minutes without needing to change any production code.

**Comment by horsburgh** [comment] 2018-01-24 20:56
@SRGDamia1 and @aufdenkampe - this is not a bug. It's a misunderstanding about how often those elements of the page need to update. @jcaraballo17 and @fryarludwig found that the performance we get from the InfluxDB is actually quite good, so they started using it as the source of data for multiple elements on the page to speed up the page loads. But, the original plan was to only update the InfluxDB periodically. So, obviously, the sparklines, CSVs, etc. are not going to reflect the most recently added data values because the InfluxDB is not being updated instantaneously. This was an oversight because those elements should be updating.

So - we are looking into updating the InfluxDB cache at the same time as the ODM2 database (i.e., when sensors POST data it will get written to ODM2 and the InfluxDB at the same time. Eventually, we may want to use the ODM2 database for all of the metadata but store all of the datavalues in the InfluxDB for performance reasons.

**Comment by fryarludwig** [comment] 2018-01-24 21:25
As of yesterday afternoon we've decreased the production influx database update time to 30 minutes. The sparklines and table will be accurate to the last 30-minute period - just as a temporary measure for responsiveness. Juan and I now are working on removing this time delay entirely. 

The Influx database stores the time series for each sensor under their respective UUID. We can pull the sensor UUIDs from each post request with their data value and timestamp, then store that in the influx database at the exact point in which we receive the data. Note that this will help the missing data issue, but will not fix the issue entirely - and this is by design. 
 
The Influx database is actually a "loose" form of storage, and is not meant to be a perfectly accurate accounting of each data value. Depending on the usage, you may lose data values, overwrite data values, and/or get stale data. This is an intentional decision by the influx team and was accepted for our use case - querying potentially millions of data points and giving the user that data near-instantly. For perfectly guaranteed and accurate data, download the CSV file for your sensor value, which pulls the data from out Postgres database (which is why it takes to so long to generate the file). 

For more information about the tradeoffs Influx makes, please read https://docs.influxdata.com/influxdb/v1.4/concepts/insights_tradeoffs/

**Comment by SRGDamia1** [comment] 2018-01-24 21:47
Thank you for the explanation.  I thought only TSA drew data from influx so I was expecting the sparklines to be instant.

**Comment by aufdenkampe** [comment] 2018-01-26 20:50
Yes, thanks for that explanation, and for increasing the update frequency to InfluxDB. It makes sense.

**Comment by jcaraballo17** [comment] 2018-02-05 17:06
Moving this to milestone 0.5 since it's not technically a bug.

**Comment by jcaraballo17** [comment] 2018-02-05 17:10
The streaming service now adds the data points directly to InfluxDB. This eliminates the necessity of an updater running every 30 minutes, and keeps the sparklines and tables updated with the most recent measurements as soon as they are received.

**Comment by SRGDamia1** [comment] 2018-02-14 21:54
Um.  Is there a separate url for the sandbox?  Should I use http://envirodiysandbox.usu.edu/api/data-stream/?

**Comment by horsburgh** [comment] 2018-02-14 21:57
Yes there should be a separate URL. What you have looks right but @jcaraballo17 can confirm if you have errors.

**Comment by jcaraballo17** [comment] 2018-02-14 22:52
@SRGDamia1 Yes, http://envirodiysandbox.usu.edu/api/data-stream/ is the right url for the sandbox.

**Comment by aufdenkampe** [comment] 2018-02-20 18:31
@SRGDamia1, have you been able to test this?

**Comment by jcaraballo17** [comment] 2018-02-21 16:54
@SRGDamia1  @aufdenkampe you can send a post request with an application like [Postman](https://www.getpostman.com/) without setting up a Mayfly with real sensors. It's basically the same since the web service doesn't care where the request is coming from. Let me know and I can help you build a request if you decide to use that app instead.

**Comment by SRGDamia1** [comment] 2018-02-22 02:44
I'm sorry this took me so long.  A few quick tests with Postman look good.

**Comment by aufdenkampe** [comment] 2018-02-22 17:54
@jcaraballo17, thanks for suggesting Postman. In the future, if you are doing your own testing of similar  "live" features on Sandbox, it would be great if you could point us to the URL of that testing site, to avoid these kinds of bottle-necks in testing. Thanks.

@SRGDamia1 , thanks for testing!

**Closed** 2018-02-27 22:03 UTC
Labels: close me, ready for testing
