### ISSUE TITLE
LOTS of jquery and bootstrap errors/warnings

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#414] opened 2019-07-30 15:02 UTC
When loading a site page on staging firefox with developer tools turned on, I'm seeing an enormous number of warnings from jquery and bootstrap.  The page appears to be fine, but I'm guessing all the warnings mean something.

**Comment by aufdenkampe** [comment] 2019-07-30 15:21
@SRGDamia1, thanks for letting us know. We'll look into it.

**Comment by jcaraballo17** [comment] 2019-08-01 18:54
@SRGDamia1 I'm seeing these warning whenever I go to to a site details page on Firefox.

![image](https://user-images.githubusercontent.com/4700505/62319295-a7217980-b46b-11e9-8a97-edd1a969b36f.png)

Are these the warnings you're seeing? The `.map` files are there to help the browsers debug a minified javascript file. Looks like Mauriel never included the map files for some of the javascript libraries he included, but they're not essential to anything related to the actual webpage.

**Comment by SRGDamia1** [comment] 2019-08-01 19:23
![image](https://user-images.githubusercontent.com/5374350/62321296-4a748d80-b470-11e9-9ccc-53923cca06cc.png)

**Comment by SRGDamia1** [comment] 2019-08-01 19:25
I get lots and lots of errors like these on all of the pages on staging.  The pages do seem to look right, but it's a lot of errors.

**Comment by aufdenkampe** [comment] 2019-08-01 19:33
@SRGDamia1, thanks for that feedback and screenshot of your errors.
Let's put this one on the back burner, given that @jcaraballo17 doesn't see the same errors as you and it all seems to be working for you anyways.

**Comment by tslawecki** [comment] 2019-08-01 19:37
One question for @SRGDamia1 - what browser are you using? There's a little bit of [StackOverflow](https://stackoverflow.com/questions/38536775/bootstrap-3-3-6-warnings-and-errors-in-bootstrap-min-css) discussion of these types of errors arising in Firefox.

**Comment by SRGDamia1** [comment] 2019-08-01 19:44
I'm a Firefox junky; I only use other browsers when forced and then I tend to whine about it.

**Comment by aufdenkampe** [comment] 2022-03-21 21:23
@xaviernogueira, can you reproduce any errors like the ones @SRGDamia1 reported on in https://github.com/ODM2/ODM2DataSharingPortal/issues/414#issuecomment-517423549?

We've very substantially updated our code and deployment since then (2019), but there's a still a surprising amount of code that we haven't yet touched.  If there are still any errors like this, it would be worth sharing with @ptomasula.

**Comment by ptomasula** [comment] 2022-04-13 16:55
This was resolved in commit [a313199](https://github.com/ODM2/ODM2DataSharingPortal/commit/a313199cf4c32f8fdd94e8bc967ae449a0771cd1) and is now on the staging server. 

As indicated in the commit notes, there were a bunch of bootstrap related files missing from the repository.

**Closed by ptomasula** 2022-04-13 16:55 UTC
Labels: question
