### ISSUE TITLE
Set up email or SMS notifications for data loss

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#77] opened 2017-08-10 22:56 UTC
- Need ability to turn on or off for site
- Need to figure out thresholds
    - Time-based (if no reporting for X-time)
    - Variable based?
        - Could get complicated
        - Skip for now?
    - User adjusted?
- Messaging text in notifications 
    - Link to site (i.e. http://data.envirodiy.org/sites/6/)
    - for how to turn on/off

**Comment by aufdenkampe** [comment] 2017-08-14 18:43
We discussed prioritizing this in our 2017-08-10 EnviroDIY Data Portal call.

**Comment by horsburgh** [comment] 2017-08-15 06:04
I think email notifications is potentially doable using our existing system, but SMS texting may be a bit more tricky as I think there are limited options for sending SMS texts for free via code. So, the details are as follows:

1. When a user registers a new site, they choose whether they want to receive notifications for that site (simple check box, yes or no).
2. When the criteria for a message to be sent are met, the application sends a notification email to the user that owns the site notifying them that data have not been received within a time window that exceeds the threshold that they set.

For now, we will only plan on doing time-based notifications. The user may configure the amount of time that must pass without a new observation before a notification message is sent. This should be done via the site registration page.

Architecturally, this may require standup of an additional offline script that is not part of the website, but runs on an application server. The script would monitor each site for which notifications have been set up, query the database to make the necessary conditional checks, and send notifications when needed.

**Comment by aufdenkampe** [comment] 2017-08-15 20:00
@horsburgh, that sounds good. This could be a given a lower priority than the other issues in Milestone 0.5, https://github.com/ODM2/ODM2WebSDL/milestone/5.

**Comment by horsburgh** [comment] 2018-01-12 20:21
@fryarludwig - I see you added the "ready for testing" label to this one. Can you please provide a brief summary of the approach that has been implemented to address this issue?

**Comment by fryarludwig** [comment] 2018-01-12 21:36
We've added an option to the site edit/registration page:
![image](https://user-images.githubusercontent.com/8953221/34895144-a0adc4e2-f7a1-11e7-90b9-e2beeb62ee60.png)

Users can choose how many hours can pass without receiving data for a site. The notification is per site -
 it's based on the most recent datavalue from any sensor. If the site as a whole exceeds that time threshold an email is sent out to the site owner. Only one email per "incident" will be sent, that way we aren't spamming people every hour or so

**Comment by horsburgh** [comment] 2018-01-12 21:38
Is there a text label somewhere to indicate what "Notify" means and what the "Hours threshold" is?

**Comment by fryarludwig** [comment] 2018-01-12 21:52
Great feedback, we'll update the text so it's self-explanatory.

**Comment by aufdenkampe** [comment] 2018-01-16 23:57
@fryarludwig, thanks for sharing your plan as you develop it. I imagine it could be quite helpful to use these GitHub issues for this kind of feedback as you are working on an issues, even before they are ready for testing.

**Comment by fryarludwig** [comment] 2018-01-18 19:44
This is the updated wording, are there any changes you'd recommend?

![image](https://user-images.githubusercontent.com/8953221/35117840-1a387456-fc4d-11e7-82b8-4454b4396587.png)

**Comment by horsburgh** [comment] 2018-01-18 19:57
"Notify me if site stops receiving sensor data"

**Comment by fryarludwig** [comment] 2018-01-18 20:59
This is fixed and on the development branch now, if you're satisfied we can close this issue.

![image](https://user-images.githubusercontent.com/8953221/35121179-c90d1c98-fc57-11e7-8da6-5e350e715540.png)

**Comment by horsburgh** [comment] 2018-01-19 00:38
I would prefer to close these when tested on the sandbox.

**Comment by SRGDamia1** [comment] 2018-02-12 15:32
The check box looks good.  When attempting to actually set up a notification I get this error:


Request Method: | POST
-- | --
http://envirodiysandbox.usu.edu/sites/update/WCC019/
1.11.7
ValidationError
[u'Select a valid choice. That choice is not one of the available choices.']
/usr/local/lib/python2.7/dist-packages/django/forms/models.py in to_python, line 1245
/usr/bin/python
2.7.12
['/opt/websdlenvironment/ODM2WebSDL/src',  '/usr/local/bin',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']
Mon, 12 Feb 2018 09:30:37 -0600

**Comment by SRGDamia1** [comment] 2018-02-12 15:33
And the error isn't a pretty "go back and fix it" error, it's an ugly django-things-are-broken type error page.

**Comment by jcaraballo17** [comment] 2018-02-12 15:54
There's something else causing that. I'll find out what the problem is, in the meantime your site is fixed and you can keep testing this.

**Comment by jcaraballo17** [comment] 2018-02-12 16:56
All sites are fixed now.

**Comment by SRGDamia1** [comment] 2018-02-12 20:25
I added alerts on the sites visible to the sandbox, but I haven't gotten any alerts yet.  I know the sandbox is an old instance of the database, is it checking that there has been no data received to the sandbox version of the database or to the live version of the database?

**Comment by aufdenkampe** [comment] 2018-02-14 19:15
@jcaraballo17 & @Maurier, can you let @SRGDamia1 know if she should expect to get notifications from Sandbox. See her question in https://github.com/ODM2/ODM2WebSDL/issues/77#issuecomment-365050940

**Comment by jcaraballo17** [comment] 2018-02-14 21:29
I'll have the email sending script scheduled on the sandbox later today. Sorry for the delay, I'm trying to figure out the best way of doing this.

**Comment by SRGDamia1** [comment] 2018-02-14 21:48
Um. Ok.  I'm sorry, I thought it was already set up.

**Comment by aufdenkampe** [comment] 2018-02-14 22:14
@jcaraballo17, the code for this issue wasn't deployed on the Sandbox?
I thought everything related to this milestone should have been deployed to Sandbox over a week ago?

**Comment by jcaraballo17** [comment] 2018-02-16 00:44
@aufdenkampe Yes, all the code is already deployed on the sandbox. The script is up there, but it wasn't scheduled to run automatically. Right now I'm having some issues with the email service setup in the sandbox that I'll have to fix tomorrow.
Now, when the email server issue is fixed, the script will run every half an hour to notify via email whoever needs to be notified, this means that (for now) there might be a time gap for the emails to get sent.

**Comment by aufdenkampe** [comment] 2018-02-20 18:30
@jcaraballo17, thanks for the update and the recent fix.
@SRGDamia1, are you now getting notifications?

**Comment by horsburgh** [comment] 2018-02-20 18:39
@aufdenkampe and @SRGDamia1 - one detail that you probably didn't catch from this discussion is that we discovered just in the last week that the email server at USU that we have been using to send emails from the EnviroDIY site just quit working. I followed up with our IT guys and they told me that they have made changes that no longer allow us to send emails from the data.envirodiy.org domain. So, the notifications we had been sending (with working code) quit working because of the changes they made. I think we have a workaround, but it's going to require sending the notifications from an email on the usu.edu domain - something like alerts.envirodiy@usu.edu and password.envirodiy@usu.edu. Juan is working on setting this up now, so it might not be completely fixed on the sandbox yet.

**Comment by aufdenkampe** [comment] 2018-02-20 18:53
@horsburgh, thanks for that extra information. Please let us know when we should expect to see this all working. I would very much like to get the Release 0.5 on Production ASAP.

**Comment by jcaraballo17** [comment] 2018-02-21 16:27
The email problem has been fixed and the script is running!
I set the script to run every 15 minutes instead of 30, so now there's a smaller gap.
@SRGDamia1 you should be getting an email soon. Let me know if you would like to change the contents of the email or the email address it's been sent from.

**Comment by SRGDamia1** [comment] 2018-02-22 02:45
I got the email.  I just sent it some more data, we'll see if it sends me another in a bit over an hour.

**Comment by jcaraballo17** [comment] 2018-02-27 22:09
Script already running and tested in production.

**Closed by jcaraballo17** 2018-02-27 22:09 UTC
Labels: close me, epic, feature request, fixed, ready for testing
