### ISSUE TITLE
Filtering leaf pack data by organization causes site markers to disappear

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#276] opened 2018-06-27 21:19 UTC
On the Browse Sites page, if you check the Leaf Pack data types box, you can see the site markers for the leaf pack experiments. If you then add an organization filter (check Stroud Water Research Center or Utah Water Research Laboratory), all site markers disappear. Uncheck the organization and the site markers reappear.

**Comment by horsburgh** [comment] 2018-08-02 00:39
I think this is working as intended now. If you select an organization for which there are no sites with leaf pack data, there should be no markers on the map. If you choose UWRL or Stroud, you should see some sites with leaf pack data. 

I'm adding the "tested" label to this one.

**Comment by HeatherBrooks** [comment] 2018-08-02 13:14
I'm still seeing the problem. If I go to Browse Sites (either logged in or not), and check Leaf Pack under Data Types, three markers are displayed. If I then add an Organization filter (I selected Stroud) all markers disappear. If I uncheck the organization, the markers reappear.

**Comment by horsburgh** [comment] 2018-08-02 14:38
When I do this same thing on http://envirodiysandbox.usu.edu, it zooms me into one site, which I assume to be the one site that has Leaf Pack data for a site from Stroud.

**Comment by HeatherBrooks** [comment] 2018-08-02 14:44
Sorry, you're right. I wasn't on the sandbox site. It works fine there.

**Comment by horsburgh** [comment] 2018-08-02 14:47
Great - I was wondering if it was a caching issue or something. Thanks for taking another look!

**Comment by horsburgh** [comment] 2018-08-14 14:33
I believe that this has been resolved and isn't occurring on the production server. Closing.

**Closed by horsburgh** 2018-08-14 14:33 UTC
Labels: bug, in progress, tested
