### ISSUE TITLE
New sensor button “+” not working

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#478] opened 2020-04-14 21:20 UTC
On attempting to create a new sensor - there is no response, fails.
I've created a new site successfully - [https://monitormywatershed.org/sites/tu_id01/](url)
Then I step in to the Manage Sensors.
https://monitormywatershed.org/sites/update/tu_id01/sensors/
As its new there are no sensors 
I hover over the + button, and it indicates "add new sensor".  When pressed there is no action  to create the first new sensor. However there is no result when pressing the '+' button
Initially two days ago, it then started working and I created 9 sensors.

Now today I need to add two more sensors, and again it “+” button is not working, and even after delaying and trying over two hours, is still not working.

**Comment by neilh10** [comment] 2020-05-18 21:47
Trying again today. I can create a new site, however new sensor fails,  no response from the "+"
Pressing Upload a file, causes a file selection box to open. 
Afterwards, still no action after pressing "+".

**Comment by neilh10** [comment] 2020-05-19 00:19
I had the site code as  LCC45-test02
and changed to LCC45test02
which gives me a URL
https://monitormywatershed.org/sites/update/LCC45test02/sensors/
and now it the "+" works.

**Comment by SRGDamia1** [comment] 2020-05-19 18:10
Hm. @aufdenkampe

**Comment by neilh10** [comment] 2020-10-24 21:03
I think this has been fixed. I haven't had any problems last couple of sensors I've created

**Comment by aufdenkampe** [comment] 2020-10-26 13:50
Thanks for testing and closing this issue. It had fallen off my radar!

**Comment by neilh10** [comment] 2020-10-26 23:58
Hey you are welcome. In a past life, we had the process the person solving marked it as fixed, but the originator was the one that should close it. :)

**Comment by HeatherBrooks** [comment] 2021-02-01 14:09
A [new report](https://www.envirodiy.org/topic/add-sensor-button-not-working-on-monitormywatershed/) of this on the EnviroDIY.org forum: "Just adding to this thread. I have had this twice. Tonight I couldn’t find a solution despite trying different browsers and incognito mode. I agree, it is a bit of a show stopper." @aufdenkampe closed this issue in October 2020; reopening.

**Comment by mbarneytu** [comment] 2021-02-01 22:32
I was curious whether opening Developer Tools (in Chrome) would show any insight to this problem. To my surprise, the Add Sensor button worked while I had DT open! One time I had to refresh the page while DT was open in order to get the Add Sensor dialog to display.

**Comment by HeatherBrooks** [comment] 2021-02-01 22:40
@mbarneytu reported a clue/temporary workaround on the EnviroDIY forum: "I was curious whether opening Developer Tools (in Chrome) would show any insight to this problem. To my surprise, the Add Sensor button worked while I had DT open! One time I had to refresh the page while DT was open in order to get the Add Sensor dialog to display. Might be a workaround until the problem gets fixed."

**Comment by aufdenkampe** [comment] 2021-02-01 23:42
@HeatherBrooks, thanks for reopening! It's a bummer that this is happening again.

@mbarneytu, thanks for sharing that temporary workaround! It could also be a clue to how to fix it.

**Comment by neilh10** [comment] 2021-11-18 04:28
I think this is fixed, I haven't seen it recently.

**Comment by aufdenkampe** [comment] 2021-11-29 22:15
Let's close this. It seems to have been caused by a caching issue.

**Closed by aufdenkampe** 2021-11-29 22:15 UTC
Labels: bug, high priority

**Comment by ptomasula** [comment] 2021-11-29 22:16
Caching to be resolved under #529
