### ISSUE TITLE
Remove abandoned leaf pack experiment variables

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#337] opened 2018-11-07 20:41 UTC
We abandoned "Content" and "Deployment Type" and removed them from the leaf pack experiment data entry form, but they still appear in the Macroinvertebrate Data section on the experiment page, the Manage Leaf Pack Experiments page, and on the site page.

![abandoned-variable-experiment](https://user-images.githubusercontent.com/9368629/48158453-8a6f6100-e2a0-11e8-84eb-b135f77fbed6.JPG)

![abandoned-variable-site](https://user-images.githubusercontent.com/9368629/48158374-5c8a1c80-e2a0-11e8-9f0d-6614186a69cb.JPG)

I don't know if this is possible, but it would be great if instead of displaying Content and Deployment Type columns in the experiment listing on the site page, you displayed the numbers from the Summary table at the bottom of the experiment page (Total Number of Individuals Found, Biotic Index, Water Quality Category (this could be shortened to Excellent, Good, Fair, or Poor), Percent EPT). That way people could see at a glance how repeat experiments at a single site compare.

**Comment by aufdenkampe** [comment] 2018-11-12 23:08
Is this connected to the "regression" that @horsburgh mentioned in https://github.com/ODM2/ODM2DataSharingPortal/issues/336#issuecomment-436726825?

@Maurier, is there an understanding of how this happened? I'm asking because we would like to learn from it for future releases.

**Comment by Maurier** [comment] 2018-11-13 17:06
@aufdenkampe This issue is not connected to #336. This was an oversight after removing the form items. We could implement the suggestion above. A quick mock-up of the suggestion would be very helpful.

**Comment by HeatherBrooks** [comment] 2018-11-13 17:30
@Maurier Here's a mock-up of what I suggested for the "Macroinvertebrate Data at This Site" section (data is from one of my tests, [http://monitormywatershed.org/sites/BogBrook_Rt312/leafpack/4/](url)

![experiment-at-glance](https://user-images.githubusercontent.com/9368629/48431442-b62a9500-e73f-11e8-815c-a599bc819b08.JPG)

If you think you have enough room, you could display the full water quality category name, e.g. "Fair - Substantial pollution likely"

**Comment by HeatherBrooks** [comment] 2019-07-29 18:39
I stated back in the original issue that "Content" and "Deployment Type" had been abandoned and should be removed from display, and I just verified on staging that has been done. 

Unfortunately, as I noted (seven months later, sorry!) in #408, I was wrong about "Deployment Type." It is still being used, albeit for a different datum than I expected, so it needs to be displayed, and the label needs to be changed to "Stream Habitat Type."

Not sure if this should be left alone for this release and addressed when the rest of #408 is in progress?

**Comment by aufdenkampe** [comment] 2019-07-29 19:01
@HeatherBrooks, thanks for testing and connecting the dots between issues.

I think we will close this issue as is for now, in the interest of getting this bug fix release out, and then address #408 with the next release 0.11.

**Closed by aufdenkampe** 2019-07-29 19:01 UTC
Labels: fixed
